package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"go.infratographer.com/example-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// FindExampleByID is the resolver for the findExampleByID field.
func (r *entityResolver) FindExampleByID(ctx context.Context, id gidx.PrefixedID) (*generated.Example, error) {
	panic(fmt.Errorf("not implemented: FindExampleByID - findExampleByID"))
}

// FindTenantByID is the resolver for the findTenantByID field.
func (r *entityResolver) FindTenantByID(ctx context.Context, id gidx.PrefixedID) (*Tenant, error) {
	panic(fmt.Errorf("not implemented: FindTenantByID - findTenantByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
