package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"go.infratographer.com/example-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ExampleCreate is the resolver for the exampleCreate field.
func (r *mutationResolver) ExampleCreate(ctx context.Context, input generated.CreateExampleInput) (*ExampleCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ExampleCreate - exampleCreate"))
}

// ExampleUpdate is the resolver for the exampleUpdate field.
func (r *mutationResolver) ExampleUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateExampleInput) (*ExampleUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ExampleUpdate - exampleUpdate"))
}

// ExampleDelete is the resolver for the exampleDelete field.
func (r *mutationResolver) ExampleDelete(ctx context.Context, id gidx.PrefixedID) (*ExampleDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ExampleDelete - exampleDelete"))
}

// Example is the resolver for the example field.
func (r *queryResolver) Example(ctx context.Context, id gidx.PrefixedID) (*generated.Example, error) {
	panic(fmt.Errorf("not implemented: Example - example"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
