package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"go.infratographer.com/example-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// FindTenantByID is the resolver for the findTenantByID field.
func (r *entityResolver) FindTenantByID(ctx context.Context, id gidx.PrefixedID) (*Tenant, error) {
	return &Tenant{ID: id}, nil
}

// FindTodoByID is the resolver for the findTodoByID field.
func (r *entityResolver) FindTodoByID(ctx context.Context, id gidx.PrefixedID) (*generated.Todo, error) {
	return r.client.Todo.Get(ctx, id)
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
